samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Standard_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Standard_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Standard_1a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Standard_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_1a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_1a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_1b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_1b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Standard_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Standard_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Standard_2a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Standard_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_2a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_2a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Standard_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Standard_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Standard_2b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Standard_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_2b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_2b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Standard_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Standard_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Standard_3a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Standard_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Standard_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Standard_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Standard_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_3a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_3a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Control_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Control_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Control_3b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Control_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Control_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Control_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Control_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_PB_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_PB_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_PB_3b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_PB_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_PB_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_PB_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_PB_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.unaligned.txt > read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/mealworm_Styrofoam_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/mealworm_Styrofoam_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/mealworm_Styrofoam_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_1a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_1a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_1a.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_1a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_1a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_1a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_1a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_1a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_1a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_1a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_1a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_1a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_1b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_1b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_1b.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_1b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_1b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_1b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_1b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_1b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_1b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_1b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_1b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_1b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_2a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_2a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_2a.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_2a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_2a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_2a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_2a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_2a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_2a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_2a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_2a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_2a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_2b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_2b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_2b.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_2b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_2b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_2b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_2b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_2b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_2b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_2b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_2b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_2b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_3a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_3a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_3a.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_3a.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_3a.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_3a.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_3a.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_3a_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_3a_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_3a_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_3a.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_3a_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Standard_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Standard_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Standard_3b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Standard_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Standard_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Standard_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Standard_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Control_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Control_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Control_3b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Control_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Control_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Control_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Control_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_PB_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_PB_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_PB_3b.unaligned.txt > read_preprocessing/insect_alignment/superworm_PB_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_PB_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_PB_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_PB_3b_R2.cleaned.fastq
samtools view -@ 16 -f 12 -F 256 read_preprocessing/insect_alignment/superworm_Styrofoam_3b.bam | cut -f1,1 > read_preprocessing/insect_alignment/superworm_Styrofoam_3b.unaligned.txt
sort -u --parallel=16 read_preprocessing/insect_alignment/superworm_Styrofoam_3b.unaligned.txt > read_preprocessing/insect_alignment/superworm_Styrofoam_3b.unaligned.sorted.txt
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_3b_R1.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_3b_R1.cleaned.fastq
pullseq -i read_preprocessing/trimmomatic_output/superworm_Styrofoam_3b_R2.bbduk.trimmed.fastq.gz -n read_preprocessing/insect_alignment/superworm_Styrofoam_3b.unaligned.sorted.txt > read_preprocessing/cleaned_reads/superworm_Styrofoam_3b_R2.cleaned.fastq

