pullseq -i metagenome_assemblies_100/mealworm_Standard_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Standard_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Standard_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Standard_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Standard_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Standard_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Standard_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Standard_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Control_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Control_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_PB_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_PB_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/mealworm_Styrofoam_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/mealworm_Styrofoam_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_1a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_1a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_1b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_1b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_2a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_2a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_2b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_2b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_3a/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_3a_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Standard_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Standard_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Control_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Control_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_PB_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_PB_3b_2.5K.fasta
pullseq -i metagenome_assemblies_100/superworm_Styrofoam_3b/scaffolds.fasta -m 2500 > metagenome_assemblies_100/reduced_assemblies/superworm_Styrofoam_3b_2.5K.fasta

