sh scripts/binning_mealworm.sh 32 mealworm_Standard_1a
sh scripts/binning_mealworm.sh 32 mealworm_Control_1a
sh scripts/binning_mealworm.sh 32 mealworm_PB_1a
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_1a
sh scripts/binning_mealworm.sh 32 mealworm_Control_1b
sh scripts/binning_mealworm.sh 32 mealworm_PB_1b
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_1b
sh scripts/binning_mealworm.sh 32 mealworm_Standard_2a
sh scripts/binning_mealworm.sh 32 mealworm_Control_2a
sh scripts/binning_mealworm.sh 32 mealworm_PB_2a
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_2a
sh scripts/binning_mealworm.sh 32 mealworm_Standard_2b
sh scripts/binning_mealworm.sh 32 mealworm_Control_2b
sh scripts/binning_mealworm.sh 32 mealworm_PB_2b
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_2b
sh scripts/binning_mealworm.sh 32 mealworm_Standard_3a
sh scripts/binning_mealworm.sh 32 mealworm_Control_3a
sh scripts/binning_mealworm.sh 32 mealworm_PB_3a
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_3a
sh scripts/binning_mealworm.sh 32 mealworm_Control_3b
sh scripts/binning_mealworm.sh 32 mealworm_PB_3b
sh scripts/binning_mealworm.sh 32 mealworm_Styrofoam_3b
sh scripts/binning_superworm.sh 32 superworm_Standard_1a
sh scripts/binning_superworm.sh 32 superworm_Control_1a
sh scripts/binning_superworm.sh 32 superworm_PB_1a
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_1a
sh scripts/binning_superworm.sh 32 superworm_Standard_1b
sh scripts/binning_superworm.sh 32 superworm_Control_1b
sh scripts/binning_superworm.sh 32 superworm_PB_1b
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_1b
sh scripts/binning_superworm.sh 32 superworm_Standard_2a
sh scripts/binning_superworm.sh 32 superworm_Control_2a
sh scripts/binning_superworm.sh 32 superworm_PB_2a
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_2a
sh scripts/binning_superworm.sh 32 superworm_Standard_2b
sh scripts/binning_superworm.sh 32 superworm_Control_2b
sh scripts/binning_superworm.sh 32 superworm_PB_2b
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_2b
sh scripts/binning_superworm.sh 32 superworm_Standard_3a
sh scripts/binning_superworm.sh 32 superworm_Control_3a
sh scripts/binning_superworm.sh 32 superworm_PB_3a
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_3a
sh scripts/binning_superworm.sh 32 superworm_Standard_3b
sh scripts/binning_superworm.sh 32 superworm_Control_3b
sh scripts/binning_superworm.sh 32 superworm_PB_3b
sh scripts/binning_superworm.sh 32 superworm_Styrofoam_3b

